[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sage-conf"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {file = ["VERSION.txt"]}
